--------------------------------------------------------
--  Fichier créé - mardi-janvier-05-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMINISTRATEUR
--------------------------------------------------------

  CREATE TABLE "OMAR"."ADMINISTRATEUR" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHAISE
--------------------------------------------------------

  CREATE TABLE "OMAR"."CHAISE" 
   (	"NUMERO" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"ID_SALLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ASSISTANT
--------------------------------------------------------

  CREATE TABLE "OMAR"."ASSISTANT" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"NBRH" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PCINEMA
--------------------------------------------------------

  CREATE TABLE "OMAR"."PCINEMA" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"REFERENCE" VARCHAR2(20 BYTE), 
	"DATEC" VARCHAR2(20 BYTE), 
	"DESTINATION" VARCHAR2(20 BYTE), 
	"NOMBRE_SALLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FILM
--------------------------------------------------------

  CREATE TABLE "OMAR"."FILM" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DUREE" NUMBER, 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "OMAR"."CLIENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"AGE" VARCHAR2(20 BYTE), 
	"LAS_NAME" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE), 
	"NUMERO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONSOMATION
--------------------------------------------------------

  CREATE TABLE "OMAR"."CONSOMATION" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"QUANTITE" NUMBER, 
	"PRIX" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCTEUR
--------------------------------------------------------

  CREATE TABLE "OMAR"."PRODUCTEUR" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"TELF" VARCHAR2(20 BYTE), 
	"ADRESS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROJECTION
--------------------------------------------------------

  CREATE TABLE "OMAR"."PROJECTION" 
   (	"ID" VARCHAR2(20 BYTE), 
	"ID_FILM" VARCHAR2(20 BYTE), 
	"ID_CINE" VARCHAR2(20 BYTE), 
	"ID_SALLE" VARCHAR2(20 BYTE), 
	"TIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALLEE
--------------------------------------------------------

  CREATE TABLE "OMAR"."SALLEE" 
   (	"NUMERO" VARCHAR2(20 BYTE), 
	"NOMBRE_DE_PLACE" VARCHAR2(20 BYTE), 
	"NOMBRE_DE_PLACE_DISPONIBLE" VARCHAR2(20 BYTE), 
	"REF_CINEMA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "OMAR"."TICKET" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PRICE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"ID_CHAISE" VARCHAR2(20 BYTE), 
	"CONSOMMATION" VARCHAR2(20 BYTE), 
	"ID_PROJEC" VARCHAR2(20 BYTE), 
	"ID_CLIENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into OMAR.ADMINISTRATEUR
SET DEFINE OFF;
Insert into OMAR.ADMINISTRATEUR (NOM,PRENOM,MAIL,ID,USERNAME,PASSWORD) values ('daghrour','gadour','gadour@esprit.tn','12345',null,null);
Insert into OMAR.ADMINISTRATEUR (NOM,PRENOM,MAIL,ID,USERNAME,PASSWORD) values ('bn','bnb','nbn','bnb','Omar','1234');
REM INSERTING into OMAR.CHAISE
SET DEFINE OFF;
REM INSERTING into OMAR.ASSISTANT
SET DEFINE OFF;
REM INSERTING into OMAR.PCINEMA
SET DEFINE OFF;
Insert into OMAR.PCINEMA (NOM,REFERENCE,DATEC,DESTINATION,NOMBRE_SALLE) values ('aaaa','a','01/01/2000','aaa','0');
REM INSERTING into OMAR.FILM
SET DEFINE OFF;
Insert into OMAR.FILM (NOM,TYPE,DUREE,ID) values ('Avengers','Action','90','1');
REM INSERTING into OMAR.CLIENT
SET DEFINE OFF;
Insert into OMAR.CLIENT (ID,AGE,LAS_NAME,NAME,MAIL,NUMERO) values ('564','20','Amara','Seif','SeifAmara@esprit.tn','1');
Insert into OMAR.CLIENT (ID,AGE,LAS_NAME,NAME,MAIL,NUMERO) values ('5','20','Dagh','Gadour','4','1');
Insert into OMAR.CLIENT (ID,AGE,LAS_NAME,NAME,MAIL,NUMERO) values ('8','1','Zahar','Youssef','5','5');
REM INSERTING into OMAR.CONSOMATION
SET DEFINE OFF;
Insert into OMAR.CONSOMATION (ID,NOM,QUANTITE,PRIX) values ('1','Popcorn','5','1.0E+001');
REM INSERTING into OMAR.PRODUCTEUR
SET DEFINE OFF;
Insert into OMAR.PRODUCTEUR (NOM,PRENOM,ID,EMAIL,TELF,ADRESS) values ('Rezgui','Skander','1234578','4','4','44');
REM INSERTING into OMAR.PROJECTION
SET DEFINE OFF;
REM INSERTING into OMAR.SALLEE
SET DEFINE OFF;
REM INSERTING into OMAR.TICKET
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ADMINISTRATEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OMAR"."ADMINISTRATEUR_PK" ON "OMAR"."ADMINISTRATEUR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHAISE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OMAR"."CHAISE_PK" ON "OMAR"."CHAISE" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ASSISTANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OMAR"."ASSISTANT_PK" ON "OMAR"."ASSISTANT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PCINEMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OMAR"."PCINEMA_PK" ON "OMAR"."PCINEMA" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FILM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OMAR"."FILM_PK" ON "OMAR"."FILM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "OMAR"."CLIENT_PK1" ON "OMAR"."CLIENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONSOMATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OMAR"."CONSOMATION_PK" ON "OMAR"."CONSOMATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCTEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OMAR"."PRODUCTEUR_PK" ON "OMAR"."PRODUCTEUR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROJECTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OMAR"."PROJECTION_PK" ON "OMAR"."PROJECTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SALLEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OMAR"."SALLEE_PK" ON "OMAR"."SALLEE" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OMAR"."TICKET_PK" ON "OMAR"."TICKET" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMINISTRATEUR
--------------------------------------------------------

  ALTER TABLE "OMAR"."ADMINISTRATEUR" ADD CONSTRAINT "ADMINISTRATEUR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OMAR"."ADMINISTRATEUR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "OMAR"."ADMINISTRATEUR" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "OMAR"."ADMINISTRATEUR" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "OMAR"."ADMINISTRATEUR" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHAISE
--------------------------------------------------------

  ALTER TABLE "OMAR"."CHAISE" ADD CONSTRAINT "CHAISE_PK" PRIMARY KEY ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ASSISTANT
--------------------------------------------------------

  ALTER TABLE "OMAR"."ASSISTANT" ADD CONSTRAINT "ASSISTANT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OMAR"."ASSISTANT" MODIFY ("NBRH" NOT NULL ENABLE);
  ALTER TABLE "OMAR"."ASSISTANT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "OMAR"."ASSISTANT" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "OMAR"."ASSISTANT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "OMAR"."ASSISTANT" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PCINEMA
--------------------------------------------------------

  ALTER TABLE "OMAR"."PCINEMA" ADD CONSTRAINT "PCINEMA_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FILM
--------------------------------------------------------

  ALTER TABLE "OMAR"."FILM" ADD CONSTRAINT "FILM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OMAR"."FILM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "OMAR"."CLIENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "OMAR"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONSOMATION
--------------------------------------------------------

  ALTER TABLE "OMAR"."CONSOMATION" ADD CONSTRAINT "CONSOMATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OMAR"."CONSOMATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTEUR
--------------------------------------------------------

  ALTER TABLE "OMAR"."PRODUCTEUR" ADD CONSTRAINT "PRODUCTEUR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OMAR"."PRODUCTEUR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECTION
--------------------------------------------------------

  ALTER TABLE "OMAR"."PROJECTION" ADD CONSTRAINT "PROJECTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OMAR"."PROJECTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALLEE
--------------------------------------------------------

  ALTER TABLE "OMAR"."SALLEE" ADD CONSTRAINT "SALLEE_PK" PRIMARY KEY ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OMAR"."SALLEE" MODIFY ("NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "OMAR"."TICKET" ADD CONSTRAINT "TICKET_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "OMAR"."TICKET" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CHAISE
--------------------------------------------------------

  ALTER TABLE "OMAR"."CHAISE" ADD CONSTRAINT "CHAISE_FK1" FOREIGN KEY ("ID_SALLE")
	  REFERENCES "OMAR"."SALLEE" ("NUMERO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECTION
--------------------------------------------------------

  ALTER TABLE "OMAR"."PROJECTION" ADD CONSTRAINT "PROJECTION_FK1" FOREIGN KEY ("ID_CINE")
	  REFERENCES "OMAR"."PCINEMA" ("REFERENCE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "OMAR"."PROJECTION" ADD CONSTRAINT "PROJECTION_FK3" FOREIGN KEY ("ID_SALLE")
	  REFERENCES "OMAR"."SALLEE" ("NUMERO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "OMAR"."PROJECTION" ADD CONSTRAINT "PROJECTION_FK4" FOREIGN KEY ("ID_FILM")
	  REFERENCES "OMAR"."FILM" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALLEE
--------------------------------------------------------

  ALTER TABLE "OMAR"."SALLEE" ADD CONSTRAINT "SALLEE_FK1" FOREIGN KEY ("REF_CINEMA")
	  REFERENCES "OMAR"."PCINEMA" ("REFERENCE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "OMAR"."TICKET" ADD CONSTRAINT "TICKET_FK1" FOREIGN KEY ("ID_CHAISE")
	  REFERENCES "OMAR"."CHAISE" ("NUMERO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "OMAR"."TICKET" ADD CONSTRAINT "TICKET_FK2" FOREIGN KEY ("ID_PROJEC")
	  REFERENCES "OMAR"."PROJECTION" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "OMAR"."TICKET" ADD CONSTRAINT "TICKET_FK3" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "OMAR"."CLIENT" ("ID") ON DELETE CASCADE ENABLE;
